# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: false

cache: packages

os:
  - linux

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11


matrix:
  allow_failures:
    - r: devel

notifications:
  email: false

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'options(covr.gcov = "gcov-4.9");library(covr);codecov()'