# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: false

cache: packages

os:
  - linux

r:
  - oldrel
  - release
  - devel

matrix:
  allow_failures:
    - r: devel

notifications:
  email: false

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'options(covr.gcov = "gcov-4.9");library(covr);codecov()'